heat_template_version: 2013-05-23

description: >
  A demo template to show provisioning of a single Linux instances.

parameters:
  Server_name:
    type: string
    description: sample-heat-test
    default: test-provision1
  flavor:
    type: string
    description: medium flavor
    default: "m1.medium"
  image:
    type: string
    description: rhel
    default: "f700ef81-e0c3-4d97-a2d9-336ac0b12d25"
  network_id_External_Network:
    type: string
    description: Network
    default: "050aedc2-dc2b-4da9-b074-b1b616147f05"
  availablity_zone:
    type: string
    description: Availability Zone
    default: "nova"
  #key_name:
    #type: string
    #description: 'For most clouds, the name of the key-pair to be used for the compute instance; for VMware clouds, the contents of the public SSH key for the compute instance'
    #label: SSH Key name
    #constraints:
    #- custom_constraint: nova.keypair  

resources:

  windows_ico_15Jan2015:
    type: OS::Nova::Server
    properties:
      networks:
          - port: { get_resource: network_port }
      name: { get_param: Server_name }  # Server name
      image: { get_param: image }
      flavor: { get_param: flavor }
      #availability_zone: { get_param: availablity_zone }
      #key_name: { get_param: key_name }

  network_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: network_id_External_Network }
