FROM ubuntu

RUN apt-get update

RUN apt-get install -y curl

#RUN curl -s https://download.elasticsearch.org/kibana/kibana/kibana-4.0.0-linux-x64.tar.gz | tar xz

RUN curl -s  https://download.elasticsearch.org/kibana/kibana/kibana-3.1.0.tar.gz | tar xz

RUN mv kibana-3.1.0 /kibana

EXPOSE 5601

CMD sed -i 's|^elasticsearch_url:.*$|elasticsearch_url: '"\"http://es:9200\""'|' /kibana/config/kibana.yml && /kibana/bin/kibana
